const ERROR_CODES = Object.freeze({
  TIMEOUT: 'TIMEOUT',
  REDIRECT_LOOP: 'REDIRECT_LOOP',
  DNS_FAILURE: 'DNS_FAILURE',
  SSL_FAILURE: 'SSL_FAILURE',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  INVALID_URL: 'INVALID_URL',
  INVALID_HTML: 'INVALID_HTML',
  UNKNOWN: 'UNKNOWN'
})

const CATEGORIES = Object.freeze({
  FRONTEND: 'Frontend',
  BACKEND: 'Backend',
  CMS: 'CMS',
  SERVER: 'Server',
  CDN: 'CDN',
  ANALYTICS: 'Analytics',
  LIBRARY: 'Library',
  HOSTING: 'Hosting'
})

const DEFAULT_TECH_TIMEOUT_MS = 15000
const DEFAULT_MAX_HTML_BYTES = 2 * 1024 * 1024
const DEFAULT_USER_AGENT = 'SolveBeatTechScanner/1.0'

module.exports = {
  ERROR_CODES,
  CATEGORIES,
  DEFAULT_TECH_TIMEOUT_MS,
  DEFAULT_MAX_HTML_BYTES,
  DEFAULT_USER_AGENT
}
