const ERROR_CODES = Object.freeze({
  TIMEOUT: 'TIMEOUT',
  REDIRECT_LOOP: 'REDIRECT_LOOP',
  DNS_FAILURE: 'DNS_FAILURE',
  SSL_FAILURE: 'SSL_FAILURE',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  INVALID_URL: 'INVALID_URL',
  UNKNOWN: 'UNKNOWN'
})

const SEVERITY = Object.freeze({
  HIGH: 'High',
  MEDIUM: 'Medium',
  LOW: 'Low',
  INFO: 'Info'
})

const FINDING_STATUS = Object.freeze({
  WARNING: 'Warning',
  FAIL: 'Fail',
  PASS: 'Pass',
  INFO: 'Info'
})

const SCORE_WEIGHTS = Object.freeze({
  NO_EVAL: 20,
  NO_DEBUGGER: 10,
  NO_DOCUMENT_WRITE: 10,
  NO_EXPOSED_SECRETS: 30,
  NO_UNSAFE_POSTMESSAGE: 10,
  BUNDLE_OPTIMIZATION: 10,
  NO_INLINE_JS: 10
})

const DEFAULT_JS_TIMEOUT_MS = 15000
const DEFAULT_MAX_SCRIPTS = 20
const DEFAULT_MAX_FILE_BYTES = 2 * 1024 * 1024
const DEFAULT_LARGE_BUNDLE_BYTES = 500 * 1024
const DEFAULT_CONCURRENCY = 5
const DEFAULT_MAX_HTML_BYTES = 2 * 1024 * 1024
const DEFAULT_USER_AGENT = 'SolveBeatJsScanner/1.0'

module.exports = {
  ERROR_CODES,
  SEVERITY,
  FINDING_STATUS,
  SCORE_WEIGHTS,
  DEFAULT_JS_TIMEOUT_MS,
  DEFAULT_MAX_SCRIPTS,
  DEFAULT_MAX_FILE_BYTES,
  DEFAULT_LARGE_BUNDLE_BYTES,
  DEFAULT_CONCURRENCY,
  DEFAULT_MAX_HTML_BYTES,
  DEFAULT_USER_AGENT
}
