const ERROR_CODES = Object.freeze({
  TIMEOUT: 'TIMEOUT',
  DNS_FAILURE: 'DNS_FAILURE',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  SSL_HANDSHAKE_FAILURE: 'SSL_HANDSHAKE_FAILURE',
  CERTIFICATE_UNAVAILABLE: 'CERTIFICATE_UNAVAILABLE',
  INVALID_HOSTNAME: 'INVALID_HOSTNAME',
  INVALID_URL: 'INVALID_URL',
  UNSUPPORTED_PROTOCOL: 'UNSUPPORTED_PROTOCOL',
  UNKNOWN: 'UNKNOWN'
})

const SEVERITY = Object.freeze({
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  INFO: 'info'
})

const FINDING_STATUS = Object.freeze({
  FAIL: 'fail',
  WARN: 'warn',
  PASS: 'pass'
})

const SCORE_WEIGHTS = Object.freeze({
  HTTPS_ENABLED: 20,
  CERTIFICATE_VALID: 20,
  TLS_VERSION: 20,
  CERTIFICATE_EXPIRY: 15,
  HOSTNAME_MATCH: 10,
  KEY_STRENGTH: 10,
  SIGNATURE_ALGORITHM: 5
})

const DEFAULT_SSL_TIMEOUT_MS = 15000
const DEFAULT_EXPIRY_WARN_DAYS = 30
const DEFAULT_HTTPS_PORT = 443
const MIN_RSA_KEY_BITS = 2048
const MIN_EC_KEY_BITS = 256

const WEAK_SIGNATURE_PATTERNS = Object.freeze([
  /md5/i,
  /sha1/i,
  /sha-1/i
])

const TLS_VERSIONS = Object.freeze({
  TLS10: 'TLSv1',
  TLS11: 'TLSv1.1',
  TLS12: 'TLSv1.2',
  TLS13: 'TLSv1.3'
})

module.exports = {
  ERROR_CODES,
  SEVERITY,
  FINDING_STATUS,
  SCORE_WEIGHTS,
  DEFAULT_SSL_TIMEOUT_MS,
  DEFAULT_EXPIRY_WARN_DAYS,
  DEFAULT_HTTPS_PORT,
  MIN_RSA_KEY_BITS,
  MIN_EC_KEY_BITS,
  WEAK_SIGNATURE_PATTERNS,
  TLS_VERSIONS
}
