// Object for all Default cred
const defaultVar = {
  APNS_KEY_ID: process.env.APNS_KEY_ID || '',
  APNS_TEAM_ID: process.env.APNS_TEAM_ID || '',
  APNS_BUNDLE_ID: process.env.APNS_BUNDLE_ID || 'com.app.fanziz',
  APNS_USE_PRODUCTION: process.env.APNS_USE_PRODUCTION || 'false',

  PAGINATION_LIMIT: parseInt(process.env.PAGINATION_LIMIT || 500),
  PORT: process.env.PORT || 1338,
  FRONTEND_HOST_URL: process.env.FRONTEND_HOST_URL || 'https://fanziz.fantasywl.in',
  BACKEND_URL: process.env.BACKEND_URL,
  LOGIN_HARD_LIMIT_ADMIN: 10, // Login limit for admin
  LOGIN_HARD_LIMIT: 5, // 0 = unlimited
  S3FIRSTDEPOSITREPORT: process.env.S3_FIRSTDEPOSIT_REPORT_PATH || 'report/firstDeposit/',
  s3TransactionReport: process.env.s3TransactionReport || 'report/transactionReport/',

  CRON_AUTH_TOKEN: process.env.CRON_AUTH_TOKEN || '613cb64fcf1172847d6f9306f3ae529a7ab0da4a3a44cef58feeb7951e5b5755',
  DISABLE_ADMIN_ROUTES: process.env.DISABLE_ADMIN_ROUTES === 'true',
  ENABLE_THIRD_PARTY_API_CALLS: process.env.ENABLE_THIRD_PARTY_API_CALLS || 'false',
  THRESHOLD_RATE_LIMIT: process.env.THRESHOLD_RATE_LIMIT || 5,

  s3UserSegmentReport: process.env.s3UserSegmentReport || 'report/userSegments/',

  OTP_LENGTH: process.env.OTP_LENGTH || 6,
  CACHE_1: 10, // 10 seconds
  CACHE_2: 60, // 1 minute
  CACHE_3: 3600, // 1 hour
  CACHE_4: 86400, // 1 day
  CACHE_5: 864000, // 10 days
  CACHE_6: 21600, // 6 Hours
  CACHE_7: 300, // 5 minute
  CACHE_8: 600, // 10 minute
  CACHE_9: 5, // 5 seconds,
  CACHE_10: 1800, // 30 minute
  CACHE_11: 30, // 30 seconds
  CACHE_12: 120, // 2 minute
  CACHE_13: 15, // 15 seconds

  DB_SQL_MIN_POOLSIZE: process.env.DB_SQL_MIN_POOLSIZE || 10,
  DB_SQL_MAX_POOLSIZE: process.env.DB_SQL_MAX_POOLSIZE || 85,

  ADMINS_DB_POOLSIZE: process.env.ADMINS_DB_POOLSIZE || 10,
  USERS_DB_POOLSIZE: process.env.USERS_DB_POOLSIZE || 10,
  REELS_DB_POOLSIZE: process.env.REELS_DB_POOLSIZE || 10,
  ARTICLES_DB_POOLSIZE: process.env.ARTICLES_DB_POOLSIZE || 10,
  MATCHES_DB_POOLSIZE: process.env.MATCHES_DB_POOLSIZE || 10,
  STATISTICS_DB_POOLSIZE: process.env.STATISTICS_DB_POOLSIZE || 10,
  SITEMAP_DB_POOLSIZE: process.env.SITEMAP_DB_POOLSIZE || 10,
  PLAYER_STATS_DB_POOLSIZE: process.env.PLAYER_STATS_DB_POOLSIZE || 10,
  SEO_REDIRECTION_DB_POOLSIZE: process.env.SEO_REDIRECTION_DB_POOLSIZE || 10,
  ENTERTAINMENT_DB_POOLSIZE: process.env.ENTERTAINMENT_DB_POOLSIZE || 10,
  JWT_SECRET: process.env.JWT_SECRET || 'aAbBcC@test_123',
  JWT_SECRET_USER: process.env.JWT_SECRET_USER || 'aAbBcC@test_123_User', // JWT secret for user
  JWT_VALIDITY: process.env.JWT_VALIDITY || '30d',
  REFRESH_TOKEN_VALIDITY: process.env.REFRESH_TOKEN_VALIDITY || '30d', // Refresh token validity
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || 'aAbBcC@test_123', // Refresh token secret
  S3_BUCKET_URL: process.env.S3_BUCKET_URL || '',
  S3PAYOUTOPTION: process.env.S3_PAYOUT_OPTION_PATH || 'payout-options/',
  S3PAYMENTOPTION: process.env.S3_PAYMENT_OPTIONS_PATH || 'payment-option/',

  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || '0123456789abcdef0123456789abcdef', // Encryption key
  IV_VALUE: process.env.IV_VALUE || 'abcdef9876543210abcdef9876543210', // IV value

  S3EMAILTEMPLATES: process.env.S3_EMAIL_TEMPLATES_PATH || 'email-templates/',
  s3SideBackground: process.env.S3_SIDE_BACKGROUND_PATH || 'side-background/',
  S3_USER_PROFILE_PATH: process.env.S3_USER_PROFILE_PATH || 'Users/profile',
  S3_STREAK_IMAGE_PATH: process.env.S3_STREAK_IMAGE_PATH || 'streak/',
  S3_LINGO_TYPE: process.env.S3_EMAIL_TEMPLATES_PATH || 'lingo_type/',

  S3BANNERS: process.env.S3_BANNERS_PATH || 'banners/',
  ALLOWDISKUSE: process.env.MONGODB_ALLOW_DISK_USE || false,
  DEFAULT_OTP: process.env.DEFAULT_OTP || '1234',
  STATIC_OTP: process.env.STATIC_OTP || '123456',

  PRIVATE_KEY: `-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQDUH3YJ9lSOPsof/8qyHKPG1kuAQXNLEWE4bd+VLBgbEitOwm9+
TLpzcnzweaiVfr9NIoaEydxP4ZlJF/h/7fhOuazSQRld429/k+ZzyfmpDkGIPbgK
OndPdy0AuWZoiEMXKQvSbtmbCN0isWlquW1vU7FnSJi4Dm1LbgpnL6FLgwIDAQAB
AoGBAIbHaq/PxVAQU0tbssXS7rkDJjva2k/DPjuljF9zAeoJdFz5q+/a/skl4H7H
PjemrhRrsH8k54gV9th7k5htcswhjs+beqAAS2gbkfM2gyE1py3eMW+9o7B+iurd
anml/SQburJEOqHnavIH33IfqDL21ikNo++3CIfMobKcGbhRAkEA/MrF8V4JEhWH
RYp5dl4Ykeu6+yP71Yg1ZWAqRRBzU+Mvei4I2zO/wjYiBmSY/1R++bBRLV+uybfO
eAXzq49xSQJBANbQkaSTcQfMxXB/YmADBWSxzNuxeUqhkKvUlmrC9r6tMcPDjgkw
I02bPsrkZVWtb1JUvwF2sK9j1ZFsmwXXYmsCQC3BLe6wDIg/aUqG89Ee2ueeeSt3
qd9OVgvRShVSEu2+ExvUNTonta+bSLFLh/2+93SOG0NRLDvKjw5eVWpZ/jECQQC1
bWxEun5RXyI2NHAqtQJ+HCjwOAFABhrA9Yig3M83FeIc+/HfUrfOWNr800++v/9w
YsD7hHoPd9sturNniJTHAkAY27gpCsXkQ4mBYNMmyW7SvP0u7D4J39CpM1vLBInM
SSMOg2rBkjg7SFp1Y+xtRNv6V/fYLQq2ohILPu1KkHIf
-----END RSA PRIVATE KEY-----`,
  PUBLIC_KEY: `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDUH3YJ9lSOPsof/8qyHKPG1kuA
QXNLEWE4bd+VLBgbEitOwm9+TLpzcnzweaiVfr9NIoaEydxP4ZlJF/h/7fhOuazS
QRld429/k+ZzyfmpDkGIPbgKOndPdy0AuWZoiEMXKQvSbtmbCN0isWlquW1vU7Fn
SJi4Dm1LbgpnL6FLgwIDAQAB
-----END PUBLIC KEY-----`,
  ENTITY_SPORTS_URL: process.env.ENTITY_SPORTS_URL || 'https://entity-sports-api-dev.fantasywl.in',
  ENTITY_SPORTS_TOKEN: process.env.ENTITY_SPORTS_TOKEN || '',

  DIGIO_BASE_URL: process.env.DIGIO_BASE_URL || '',
  DIGIO_CLIENT_ID: process.env.DIGIO_CLIENT_ID || '',
  DIGIO_SECRET: process.env.DIGIO_SECRET || '',
  DIGIO_WORKFLOW_NAME: process.env.DIGIO_WORKFLOW_NAME || '',
  FUNCTIONALITY: {
    USER_KYC_VISIBLE: true
  },
  ALLOW_BANK_UPDATE: (process.env.ALLOW_BANK_UPDATE === 'true'), // this flag is for admin allow to user to update bank details or not.
  TRIAL_USER_NUMBER: process.env.TRIAL_USER_NUMBER || '1234567899',
  NEWS_LETTER_COUNT: process.env.NEWS_LETTER_COUNT || 3,
  AUTO_OUTCOME_THRESHOLD: process.env.AUTO_OUTCOME_THRESHOLD || 3,
  SIMILARITY_THRESHOLD: parseFloat(process.env.SIMILARITY_THRESHOLD) || 0.8,
  RELEVANT_SIMILARITY_THRESHOLD: parseFloat(process.env.SIMILARITY_THRESHOLD) || 0.40,
  CUSTOM_DEEP_LINK_ENABLED: process.env.CUSTOM_DEEP_LINK_ENABLED || true,
  DEEP_LINK_URL: process.env.DEEP_LINK_URL || 'https://fanziz-api.fantasywl.in',

  SENTIMENT_CHECK_QUEUE_CONCURRENCY: process.env.SENTIMENT_CHECK_QUEUE_CONCURRENCY || 1,
  RSSFEED_ARTICLE_QUEUE_CONCURRENCY: process.env.RSSFEED_ARTICLE_QUEUE_CONCURRENCY || 50,
  SITEMAP_CHECK_QUEUE_CONCURRENCY: process.env.SITEMAP_CHECK_QUEUE_CONCURRENCY || 10,
  COMMENTARY_LINGO_QUEUE_CONCURRENCY: process.env.COMMENTARY_LINGO_QUEUE_CONCURRENCY || 10,
  MATCH_CARD_IMAGE_QUEUE_CONCURRENCY: process.env.MATCH_CARD_IMAGE_QUEUE_CONCURRENCY || 3,
  SENTIMENT_JOB_REPEAT_MS: process.env.SENTIMENT_JOB_REPEAT_MS || 240000, // 4 minutes
  PROCESS_ARTICLE_LIMIT: process.env.PROCESS_ARTICLE_LIMIT || 2,
  PROCESS_ERROR_ARTICLE_LIMIT: process.env.PROCESS_ERROR_ARTICLE_LIMIT || 2,
  PROCESS_SENTIMENT_ARTICLE_LIMIT: process.env.PROCESS_SENTIMENT_ARTICLE_LIMIT || 5,
  CONTENT_MODERATION_LIMIT: process.env.CONTENT_MODERATION_LIMIT || 5,
  PAGE_SIZE: process.env.PAGE_SIZE || 50,

  MAIL_TRANSPORTER: {
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || 587, 10),
    secure: String(process.env.SMTP_PORT || 587) === '465',
    requireTLS: String(process.env.SMTP_PORT || 587) !== '465',
    auth: {
      // Gmail address (full email) + App Password (spaces optional)
      user: process.env.SMTP_USERNAME || '',
      pass: (process.env.SMTP_PASSWORD || '').replace(/\s+/g, '')
    }
  },
  // For Gmail, From must match the authenticated account
  SMTP_FROM: process.env.SMTP_FROM || process.env.SMTP_USERNAME || 'noreply@solvebeat.com',
  READ_ARTICLE_TTL: process.env.READ_ARTICLE_TTL || 259200, // 3 days in seconds (60 * 60 * 24 * 3)
  READ_SHORTS_TTL: process.env.READ_SHORTS_TTL || 259200, // 3 days in seconds (60 * 60 * 24 * 3)
  READ_GAMES_TTL: process.env.READ_GAMES_TTL || 259200, // 3 days in seconds (60 * 60 * 24 * 3)
  BASE_SITEMAP: 'sitemap',
  POST_SITEMAP: 'post-sitemap',
  CRICKET_MATCH_SITEMAP: 'cricket-matches-sitemap',
  SOCCER_MATCH_SITEMAP: 'soccer-matches-sitemap',
  ENTERTAINMENT_SITEMAP: 'entertainment-sitemap',
  CT_LIVE_MATCHES_REDIS_KEY: process.env.CT_LIVE_MATCHES_REDIS_KEY || 'CT_LIVE_MATCHES',

  // Competition similar-articles cache (overview API)
  SIMILAR_ARTICLES_LIMIT: 20, // Default similar articles count for buzz/lingo APIs
  SIMILAR_ARTICLES_CACHE_LIMIT: 200, // Max article IDs cached per competition for overview
  SIMILAR_ARTICLES_MAX_CANDIDATES: 200, // Max RssFeedArticle candidates for similarity search
  COMPETITION_SIMILAR_ARTICLES_KEY: 'competition:similar-articles:', // Redis key prefix per competition
  COMPETITION_SIMILAR_ARTICLES_TTL: 3600, // Cache TTL in seconds (1 hr)
  SIMILAR_ARTICLES_CRON_LOCK_KEY: 'competition:similar-articles:cron:lock', // Prevents overlapping cron runs
  SIMILAR_ARTICLES_CRON_CURSOR_KEY: 'competition:similar-articles:cron:cursor', // Cursor for batch processing
  SIMILAR_ARTICLES_CRON_LOCK_TTL: 900, // Lock TTL in seconds (15 min)
  SIMILAR_ARTICLES_CRON_CURSOR_TTL: 86400, // Cursor key TTL (1 day) — must outlive gap between runs (e.g. 1 hr)

  ARTICLE_RELATED_REELS_LIMIT: 20, // Max reels returned per article (Fanshots)
  ARTICLE_RELATED_REELS_MAX_CANDIDATES: 200, // Max reel candidates for similarity search
  ARTICLE_RELATED_REELS_CACHE_KEY: 'article:related-reels:', // Redis key prefix per article
  ARTICLE_RELATED_REELS_TTL: 7200, // Cache TTL in seconds (2 hr)
  ARTICLE_REELS_MATCH_MAX_TERMS: 10, // Max terms (from aCategory/aMetaKeywords) for reel hashtag/title match; caps $or size for perf

  SERIES_REELS_FULL_CACHE_LIMIT: 200,
  SERIES_REELS_FULL_CACHE_TTL: 7200,
  SERIES_REELS_SIMILARITY_THRESHOLD: 0.45,
  MATCH_SIMILARITY_THRESHOLD: 0.70,
  COMPETITION_SIMILARITY_THRESHOLD: 0.70,
  SERIES_REELS_DAYS_BACK: 20,
  SERIES_REELS_WARM_CRON_LIMIT: 50,
  SERIES_REELS_CRON_LOCK_KEY: 'competition:series-reels:cron:lock',
  SERIES_REELS_CRON_CURSOR_KEY: 'competition:series-reels:cron:cursor',
  SERIES_REELS_CRON_LOCK_TTL: 900,
  SERIES_REELS_CRON_CURSOR_TTL: 86400,

  RECOMMENDED_VIDEOS_CACHE_TTL: 600, // 10 minutes

  REEL_EMBEDDING_BACKFILL_BATCH_SIZE: 20,
  REEL_EMBEDDING_BACKFILL_LIMIT: 1000,

  CONTENT_MODERATION_TEMPERATURE: process.env.CONTENT_MODERATION_TEMPERATURE || 0.4,
  CONTENT_MODERATION_MAX_TOKEN: process.env.CONTENT_MODERATION_MAX_TOKEN || 700,
  SENTIMENT_TEMPERATURE: process.env.SENTIMENT_TEMPERATURE || 0.3,
  SENTIMENT_MAX_TOKEN: process.env.SENTIMENT_MAX_TOKEN || 500,
  LINGO_CONVERSION_TEMPERATURE: process.env.LINGO_CONVERSION_TEMPERATURE || 0.5,
  LINGO_CONVERSION_MAX_TOKEN: process.env.LINGO_CONVERSION_MAX_TOKEN || 500,
  COMMENTARY_CONVERSION_TEMPERATURE: process.env.COMMENTARY_CONVERSION_TEMPERATURE || 0.5,
  COMMENTARY_CONVERSION_MAX_TOKEN: process.env.COMMENTARY_CONVERSION_MAX_TOKEN || 700,
  DESCRIPTION_REWRITE_TEMPERATURE: process.env.DESCRIPTION_REWRITE_TEMPERATURE || 0.7,
  DESCRIPTION_REWRITE_MAX_TOKEN: process.env.DESCRIPTION_REWRITE_MAX_TOKEN || 500,
  EJECT_REEL_DAYS: process.env.EJECT_REEL_DAYS || 7,
  REEL_PAGE_SIZE: process.env.REEL_PAGE_SIZE || 15,
  REMOVE_SHORTS_PROCESS_BUNCH: process.env.REMOVE_SHORTS_PROCESS_BUNCH || 100,
  REEL_S3_CLEANUP_MONTHS: process.env.REEL_S3_CLEANUP_MONTHS || 6,
  REEL_ARCHIVE_DURATION: process.env.REEL_ARCHIVE_DURATION || 6,
  REEL_ARCHIVE_DAYS: process.env.REEL_ARCHIVE_DAYS || 180,
  REEL_ARCHIVE_FILE_LIMIT: process.env.REEL_ARCHIVE_FILE_LIMIT || 5000,
  REEL_ARCHIVE_CHUNK_SIZE: process.env.REEL_ARCHIVE_CHUNK_SIZE || 500,
  S3_REEL_ARCHIVE_PATH: process.env.S3_REEL_ARCHIVE_PATH || 'archive/reels/',
  ARTICLE_ARCHIVE_DAYS: process.env.ARTICLE_ARCHIVE_DAYS || 180,
  ARTICLE_ARCHIVE_BATCH_SIZE: process.env.ARTICLE_ARCHIVE_BATCH_SIZE || 100,
  ARTICLE_ARCHIVE_CHUNK_SIZE: process.env.ARTICLE_ARCHIVE_CHUNK_SIZE || 25,
  S3_ARTICLE_ARCHIVE_PATH: process.env.S3_ARTICLE_ARCHIVE_PATH || 'archive/articles/',
  EVENT_ARCHIVE_DAYS: process.env.EVENT_ARCHIVE_DAYS || 180,
  EVENT_ARCHIVE_BATCH_SIZE: process.env.EVENT_ARCHIVE_BATCH_SIZE || 100,
  S3_LIST_MAX_KEYS: process.env.S3_LIST_MAX_KEYS || 1000,
  S3_DELETE_MAX_OBJECTS: process.env.S3_DELETE_MAX_OBJECTS || 100,
  REMOVE_ESPORTS_VIDEO_PROCESS_BUNCH: process.env.REMOVE_ESPORTS_VIDEO_PROCESS_BUNCH || 100,
  REEL_SORTED_SET_KEY: process.env.REEL_SORTED_SET_KEY || 'REEL_SET',
  REELCATEGORY_SORTED_SET_KEY: process.env.REEL_SORTED_SET_KEY || 'REELCATEGORY_SET',
  REELSUBCATEGORY_SORTED_SET_KEY: process.env.REELSUBCATEGORY_SORTED_SET_KEY || 'REELSUBCATEGORY_SET',
  SUBSCRIBE_ENVIRONMENT: process.env.SUBSCRIBE_ENVIRONMENT || 'stag',
  WEBHOOK_SIGNATURE: process.env.WEBHOOK_SIGNATURE || '2fb017c6968bab952a6140bb0728f461c940c04c8398d30e035f489ac7ddc037',
  SOCKET_SECRET: process.env.SOCKET_SECRET || '06wvD0FtLHQRbBFzdllRDb6BkJOKGLVf',
  COMMENTARY_CONVERSION_ALLOW: process.env.COMMENTARY_CONVERSION_ALLOW || false,
  MATCH_LIVE_NOTIFICATION: process.env.MATCH_LIVE_NOTIFICATION || false,

  EVENT_QUEUE_CONCURRENCY: process.env.EVENT_QUEUE_CONCURRENCY || 200,
  FOOTBALL_EVENT_QUEUE_CONCURRENCY: process.env.FOOTBALL_EVENT_QUEUE_CONCURRENCY || 200,
  AUTO_EVENT_QUEUE_CONCURRENCY: process.env.AUTO_EVENT_QUEUE_CONCURRENCY || 100,
  STAGE_REEL_ALLOW: process.env.STAGE_REEL_ALLOW || true,
  STAGE_DATA_SYNC_CT_ALLOW: process.env.STAGE_DATA_SYNC_CT_ALLOW || true,
  USER_REMINDER_TITLE: process.env.USER_MESSAGE_TITLE || 'New Message Arrived',
  S3_PRODUCTS: process.env.S3_PRODUCTS || 'products/',
  MIN_ARTICLE_THRESHOLD: 1000,
  SITEMAP_LIMIT: process.env.SITEMAP_LIMIT || 2000,

  OVER_WISE_EVENT_INACTIVE_DELAY: parseInt(process.env.OVER_WISE_EVENT_INACTIVE_DELAY || 60000), // 60 seconds in milliseconds
  MIN_ESPORTS_VIDEO_DURATION: 600, // 10 minutes in seconds
  MAX_ESPORTS_VIDEO_DURATION: 18000, // 5 hours in seconds
  MIN_VIDEO_DURATION: 120, // 2 minutes in seconds
  MAX_VIDEO_DURATION: 18000, // 5 hours in seconds
  MAX_AUDIO_AD_DURATION: 15, // 15 seconds
  AVG_VIEW_THRESHOLD_FOR_YOUTUBE: 15000,
  AVG_VIEW_THRESHOLD_FOR_TWITCH: 40458,
  USER_ACTIVITY_QUEUE_CONCURRENCY: process.env.USER_ACTIVITY_QUEUE_CONCURRENCY || 200,
  ENTERTAINMENT_DESCRIPTION_QUEUE_CONCURRENCY: process.env.ENTERTAINMENT_DESCRIPTION_QUEUE_CONCURRENCY || 50,
  TMDB_SYNC_DISPATCH_CONCURRENCY: parseInt(process.env.TMDB_SYNC_DISPATCH_CONCURRENCY || 2),
  TMDB_SYNC_MOVIE_CONCURRENCY: parseInt(process.env.TMDB_SYNC_MOVIE_CONCURRENCY || 2),
  TMDB_SYNC_SERIES_CONCURRENCY: parseInt(process.env.TMDB_SYNC_SERIES_CONCURRENCY || 2),
  TMDB_SYNC_SEASON_CONCURRENCY: parseInt(process.env.TMDB_SYNC_SEASON_CONCURRENCY || 3),
  TMDB_SYNC_PERSON_CONCURRENCY: parseInt(process.env.TMDB_SYNC_PERSON_CONCURRENCY || 3),
  TMDB_SYNC_MOVIE_RATE_PER_SEC: parseInt(process.env.TMDB_SYNC_MOVIE_RATE_PER_SEC || 3),
  TMDB_SYNC_SERIES_RATE_PER_SEC: parseInt(process.env.TMDB_SYNC_SERIES_RATE_PER_SEC || 3),
  TMDB_SYNC_SEASON_RATE_PER_SEC: parseInt(process.env.TMDB_SYNC_SEASON_RATE_PER_SEC || 4),
  TMDB_SYNC_PERSON_RATE_PER_SEC: parseInt(process.env.TMDB_SYNC_PERSON_RATE_PER_SEC || 3),
  TMDB_SYNC_WINDOW_DAYS: parseInt(process.env.TMDB_SYNC_WINDOW_DAYS || 1),
  TMDB_SYNC_OVERLAP_HOURS: parseInt(process.env.TMDB_SYNC_OVERLAP_HOURS || 1),
  TMDB_SYNC_MATCH_CHUNK: parseInt(process.env.TMDB_SYNC_MATCH_CHUNK || 200),
  TMDB_SYNC_LOCK_TTL: parseInt(process.env.TMDB_SYNC_LOCK_TTL || 1800),
  TMDB_SYNC_JOB_ATTEMPTS: parseInt(process.env.TMDB_SYNC_JOB_ATTEMPTS || 5),
  TMDB_SYNC_DISPATCH_ATTEMPTS: parseInt(process.env.TMDB_SYNC_DISPATCH_ATTEMPTS || 3),
  FIVE_MIN_FOOTBALL_EVENT_INACTIVE_DELAY: process.env.FIVE_MIN_FOOTBALL_EVENT_INACTIVE_DELAY || 300000, // 5 minutes in milliseconds
  LANGUAGE: 'en',
  POPULARITY_SERIES_THRESHOLD: 6,
  POPULARITY_MOVIE_THRESHOLD: 200,
  SENTIMENT_SIMILARITY_THRESHOLD: process.env.SENTIMENT_SIMILARITY_THRESHOLD || 0.25,
  CRICKET_MATCH_CARD_BACKGROUNDS: process.env.CRICKET_MATCH_CARD_BACKGROUNDS || ''
}
module.exports = defaultVar
