const thirdPartyCred = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '',
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || '',

  GUEST_TOKEN_VALIDITY: process.env.GUEST_TOKEN_VALIDITY || '365d',
  GUEST_FREE_SCANS: parseInt(process.env.GUEST_FREE_SCANS || 1, 10),
  GUEST_SCAN_TTL: parseInt(process.env.GUEST_SCAN_TTL || 2592000, 10),
  // How long a guest identity stays bound to an IP (rolling — refreshed on every /guest hit) before it's freed up for a new guest
  GUEST_IDENTITY_TTL_DAYS: parseInt(process.env.GUEST_IDENTITY_TTL_DAYS || 365, 10),

  OTP_EXPIRY_MINUTES: parseInt(process.env.OTP_EXPIRY_MINUTES || 5, 10),
  OTP_MAX_SEND_PER_WINDOW: parseInt(process.env.OTP_MAX_SEND_PER_WINDOW || 5, 10),
  OTP_SEND_WINDOW_MINUTES: parseInt(process.env.OTP_SEND_WINDOW_MINUTES || 15, 10),
  OTP_MAX_VERIFY_ATTEMPTS: parseInt(process.env.OTP_MAX_VERIFY_ATTEMPTS || 5, 10),

  SCAN_MODULE_TIMEOUT_MS: parseInt(process.env.SCAN_MODULE_TIMEOUT_MS || 30000, 10),
  SCAN_MODULE_MAX_ATTEMPTS: parseInt(process.env.SCAN_MODULE_MAX_ATTEMPTS || 3, 10),
  SCAN_MODULE_RETRY_BACKOFF_MS: parseInt(process.env.SCAN_MODULE_RETRY_BACKOFF_MS || 2000, 10),
  SCAN_WORKER_CONCURRENCY: parseInt(process.env.SCAN_WORKER_CONCURRENCY || 5, 10),
  SCAN_PARENT_CONCURRENCY: parseInt(process.env.SCAN_PARENT_CONCURRENCY || 2, 10),
  DEBUG_LOG: process.env.DEBUG_LOG === 'true',
  SCAN_HTTP_TIMEOUT_MS: parseInt(process.env.SCAN_HTTP_TIMEOUT_MS || 15000, 10),
  SCAN_HTTP_MAX_REDIRECTS: parseInt(process.env.SCAN_HTTP_MAX_REDIRECTS || 5, 10),
  SCAN_HTTP_USER_AGENT: process.env.SCAN_HTTP_USER_AGENT || 'SolveBeatHeaderScanner/1.0',
  SCAN_SSL_TIMEOUT_MS: parseInt(process.env.SCAN_SSL_TIMEOUT_MS || 15000, 10),
  SCAN_SSL_EXPIRY_WARN_DAYS: parseInt(process.env.SCAN_SSL_EXPIRY_WARN_DAYS || 30, 10),
  SCAN_DNS_TIMEOUT_MS: parseInt(process.env.SCAN_DNS_TIMEOUT_MS || 10000, 10),
  SCAN_TECH_TIMEOUT_MS: parseInt(process.env.SCAN_TECH_TIMEOUT_MS || 15000, 10),
  SCAN_TECH_MAX_HTML_BYTES: parseInt(process.env.SCAN_TECH_MAX_HTML_BYTES || String(2 * 1024 * 1024), 10),
  SCAN_TECH_USER_AGENT: process.env.SCAN_TECH_USER_AGENT || 'SolveBeatTechScanner/1.0',
  SCAN_JS_TIMEOUT_MS: parseInt(process.env.SCAN_JS_TIMEOUT_MS || 15000, 10),
  SCAN_JS_MAX_SCRIPTS: parseInt(process.env.SCAN_JS_MAX_SCRIPTS || 20, 10),
  SCAN_JS_MAX_FILE_BYTES: parseInt(process.env.SCAN_JS_MAX_FILE_BYTES || String(2 * 1024 * 1024), 10),
  SCAN_JS_MAX_HTML_BYTES: parseInt(process.env.SCAN_JS_MAX_HTML_BYTES || String(2 * 1024 * 1024), 10),
  SCAN_JS_LARGE_BUNDLE_BYTES: parseInt(process.env.SCAN_JS_LARGE_BUNDLE_BYTES || String(500 * 1024), 10),
  SCAN_JS_CONCURRENCY: parseInt(process.env.SCAN_JS_CONCURRENCY || 5, 10),
  SCAN_JS_USER_AGENT: process.env.SCAN_JS_USER_AGENT || 'SolveBeatJsScanner/1.0',
  SCAN_SECRET_TIMEOUT_MS: parseInt(process.env.SCAN_SECRET_TIMEOUT_MS || 15000, 10),
  SCAN_SECRET_MAX_RESOURCES: parseInt(process.env.SCAN_SECRET_MAX_RESOURCES || 20, 10),
  SCAN_SECRET_MAX_FILE_BYTES: parseInt(process.env.SCAN_SECRET_MAX_FILE_BYTES || String(2 * 1024 * 1024), 10),
  SCAN_SECRET_CONCURRENCY: parseInt(process.env.SCAN_SECRET_CONCURRENCY || 5, 10),
  SCAN_SECRET_USER_AGENT: process.env.SCAN_SECRET_USER_AGENT || 'SolveBeatSecretScanner/1.0',
  SCAN_SEO_TIMEOUT_MS: parseInt(process.env.SCAN_SEO_TIMEOUT_MS || 15000, 10),
  SCAN_SEO_MAX_HTML_BYTES: parseInt(process.env.SCAN_SEO_MAX_HTML_BYTES || String(2 * 1024 * 1024), 10),
  SCAN_SEO_LINK_CHECK_LIMIT: parseInt(process.env.SCAN_SEO_LINK_CHECK_LIMIT || 15, 10),
  SCAN_SEO_IMAGE_CHECK_LIMIT: parseInt(process.env.SCAN_SEO_IMAGE_CHECK_LIMIT || 10, 10),
  SCAN_SEO_CONCURRENCY: parseInt(process.env.SCAN_SEO_CONCURRENCY || 5, 10),
  SCAN_SEO_USER_AGENT: process.env.SCAN_SEO_USER_AGENT || 'SolveBeatSeoScanner/1.0',
  SCAN_PERF_TIMEOUT_MS: parseInt(process.env.SCAN_PERF_TIMEOUT_MS || 15000, 10),
  SCAN_PERF_MAX_HTML_BYTES: parseInt(process.env.SCAN_PERF_MAX_HTML_BYTES || String(2 * 1024 * 1024), 10),
  SCAN_PERF_MAX_RESOURCE_BYTES: parseInt(process.env.SCAN_PERF_MAX_RESOURCE_BYTES || String(2 * 1024 * 1024), 10),
  SCAN_PERF_MAX_RESOURCES: parseInt(process.env.SCAN_PERF_MAX_RESOURCES || 100, 10),
  SCAN_PERF_CONCURRENCY: parseInt(process.env.SCAN_PERF_CONCURRENCY || 5, 10),
  SCAN_PERF_USER_AGENT: process.env.SCAN_PERF_USER_AGENT || 'SolveBeatPerfScanner/1.0',
  SCAN_INFRA_TIMEOUT_MS: parseInt(process.env.SCAN_INFRA_TIMEOUT_MS || 10000, 10),
  SCAN_INFRA_USER_AGENT: process.env.SCAN_INFRA_USER_AGENT || 'SolveBeatInfraScanner/1.0',

  SENTRY_DSN: process.env.SENTRY_DSN || ''
}

module.exports = thirdPartyCred
